name: Python package tests

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        auto-update-conda: true

    - name: Initialize conda
      run: |
        conda init bash
        source ~/.bashrc
        conda activate base

    - name: Create conda environment
      run: |
        conda env create -f environment.yml
        conda activate pycontrails_env

    - name: Install test dependencies
      run: |
        conda activate pycontrails_env
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        conda activate pycontrails_env
        pytest --cov=.

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
